public class ProcessBuilderNoAction {
    
    /**
     * Explanation: This method will be invoked from the Process Builder when the Salesforce admin
     * does not want to execute any actions.
     * 
     * Once this idea is implemented https://success.salesforce.com/ideaView?id=08730000000DqGRAA0
     * this code will no longer be needed
     **/
    
    @InvocableMethod
    public static void DoNothing() {}

}