public class AccountBean implements DeviceCRMBean {
    public String Name { get; set; }
    public String CustomerNumber { get; set; }
    public String Description { get; set; }
    public String BillingStreet { get; set; }
    public String BillingCity { get; set; }
    public String BillingState { get; set; }
    public String BillingCountry { get; set; }
    public String OtherName { get; set; }
}